export type InterfaceLanguage = 'ru' | 'en'

const settingsCopy = {
  ru: {
    back: 'Назад',
    title: 'Настройки',
    personal: 'Личные данные',
    name: 'Имя',
    email: 'Email',
    password: 'Пароль',
    appearance: 'Оформление',
    dark: 'Тёмная',
    light: 'Светлая',
    darkHint: 'Основное оформление',
    lightHint: 'Для яркого света',
    selected: 'Выбрано',
    language: 'Язык интерфейса',
    languageNote: 'Эта страница переведена; остальные разделы переводятся постепенно.',
    russian: 'Русский',
    english: 'Английский',
    privacy: 'Приватность',
    publicProfile: 'Публичный профиль',
    publicProfileDescription: 'Друзья видят ваши поездки и штампы',
    activity: 'Показывать активность',
    activityDescription: 'Прогресс по странам виден в лидерборде',
    notifications: 'Уведомления',
    emailNotifications: 'На почту',
    emailNotificationsDescription: 'Итоги поездок и падение цен по копилке',
    pushNotifications: 'Push-уведомления',
    pushNotificationsDescription: 'Вопрос дня и напоминание про стрик',
    connectedServices: 'Подключённые сервисы',
    signInAndSync: 'Вход и синхронизация',
    connect: 'Подключить',
    account: 'Аккаунт',
    logout: 'Выйти из аккаунта',
    deleteAccount: 'Удалить аккаунт',
    deleteAccountDescription: 'Прогресс и штампы будут потеряны',
    deleteAccountTitle: 'Удалить аккаунт?',
    deleteAccountWarning: 'Это действие нельзя отменить. Маршруты, прогресс и штампы будут удалены навсегда.',
    cancel: 'Отмена',
    delete: 'Удалить',
    pageLabel: 'Настройки Crista',
  },
  en: {
    back: 'Back',
    title: 'Settings',
    personal: 'Personal information',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    appearance: 'Appearance',
    dark: 'Dark',
    light: 'Light',
    darkHint: 'Default appearance',
    lightHint: 'For bright environments',
    selected: 'Selected',
    language: 'Interface language',
    languageNote: 'This page is translated; other sections are being localized.',
    russian: 'Russian',
    english: 'English',
    privacy: 'Privacy',
    publicProfile: 'Public profile',
    publicProfileDescription: 'Friends can see your trips and stamps',
    activity: 'Show activity',
    activityDescription: 'Your country progress appears on the leaderboard',
    notifications: 'Notifications',
    emailNotifications: 'Email',
    emailNotificationsDescription: 'Trip summaries and savings-pot price drops',
    pushNotifications: 'Push notifications',
    pushNotificationsDescription: 'Question of the day and streak reminders',
    connectedServices: 'Connected services',
    signInAndSync: 'Sign-in and sync',
    connect: 'Connect',
    account: 'Account',
    logout: 'Sign out',
    deleteAccount: 'Delete account',
    deleteAccountDescription: 'Your progress and stamps will be lost',
    deleteAccountTitle: 'Delete your account?',
    deleteAccountWarning: 'This action cannot be undone. Your routes, progress, and stamps will be permanently deleted.',
    cancel: 'Cancel',
    delete: 'Delete',
    pageLabel: 'Crista settings',
  },
} satisfies Record<InterfaceLanguage, Record<string, string>>

export function getSettingsCopy(language: InterfaceLanguage) {
  return settingsCopy[language]
}
