import { expect, test } from '@playwright/test'

test('new player completes the server-backed St Petersburg pilot', async ({ page }) => {
  test.setTimeout(120_000)
  const email = `city-pilot-${Date.now()}@example.test`
  await page.goto('/signup')
  await page.locator('#name').fill('City pilot E2E')
  await page.locator('#email').fill(email)
  await page.locator('#password').fill('CityPilot123')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByRole('button', { name: 'Изучение мира' }).click()

  await page.getByRole('button', { name: /1\. Эрмитаж.*Открыто/ }).click()
  await expect(page.getByRole('heading', { name: 'Эрмитаж' })).toBeVisible()
  await page.getByRole('button', { name: '1764', exact: true }).click()
  await expect(page.getByText('Верно! +25 XP')).toBeVisible()
  await page.getByRole('button', { name: /2\. Петергоф.*Открыто/ }).click()
  await expect(page.getByRole('heading', { name: 'Петергоф' })).toBeVisible()
  await expect(page.getByText('Временная шкала')).toBeVisible()
  await page.getByRole('button', { name: '1723', exact: true }).click()
  await page.getByRole('button', { name: /3\. Коллекция Эрмитажа.*Открыто/ }).click()
  await page.getByRole('button', { name: 'Более 3 млн', exact: true }).click()
  await page.getByRole('button', { name: /4\. Фонтаны Петергофа.*Открыто/ }).click()
  await page.getByRole('button', { name: 'Свыше 150', exact: true }).click()
  await page.getByRole('button', { name: /5\. Первое упоминание Петергофа.*Открыто/ }).click()
  await expect(page.getByRole('heading', { name: 'Первое упоминание Петергофа' })).toBeVisible()
  await expect(page.getByText('Правда или миф')).toBeVisible()
  await page.getByRole('button', { name: 'Факт', exact: true }).click()
  await expect(page.getByText('Маршрут завершён. Все факты сохранены с первоисточниками.')).toBeVisible()
})

test('new player completes the server-backed Sochi nature pilot', async ({ page }) => {
  test.setTimeout(120_000)
  const email = `sochi-pilot-${Date.now()}@example.test`
  await page.goto('/signup')
  await page.locator('#name').fill('Sochi pilot E2E')
  await page.locator('#email').fill(email)
  await page.locator('#password').fill('SochiPilot123')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByRole('button', { name: 'Изучение мира' }).click()

  await page.getByRole('button', { name: /1\. Сочинский национальный парк.*Открыто/ }).click()
  await expect(page.getByRole('heading', { name: 'Сочинский национальный парк' })).toBeVisible()
  await page.getByRole('button', { name: '1983', exact: true }).click()
  await expect(page.getByText('Верно! +25 XP')).toBeVisible()
  await page.getByRole('button', { name: /2\. Дендрарий.*Открыто/ }).click()
  await expect(page.getByRole('heading', { name: 'Дендрарий' })).toBeVisible()
  await expect(page.getByText('Временная шкала')).toBeVisible()
  await page.getByRole('button', { name: '1892', exact: true }).click()
  await page.getByRole('button', { name: /3\. Горные леса.*Открыто/ }).click()
  await page.getByRole('button', { name: '94,1%', exact: true }).click()
  await page.getByRole('button', { name: /4\. Река Мзымта.*Открыто/ }).click()
  await page.getByRole('button', { name: '89 км', exact: true }).click()
  await page.getByRole('button', { name: /5\. Площадь национального парка.*Открыто/ }).click()
  await expect(page.getByRole('heading', { name: 'Площадь национального парка' })).toBeVisible()
  await expect(page.getByText('Правда или миф')).toBeVisible()
  await page.getByRole('button', { name: 'Факт', exact: true }).click()
  await expect(page.getByText('Маршрут завершён. Все факты сохранены с первоисточниками.')).toBeVisible()
})
